services:
  - type: web
    name: jobradar-api
    runtime: docker
    rootDir: jobradar-backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod,cloud
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "10494"
      - key: DB_NAME
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_CA_CERT_PATH
        value: ""
      - key: DB_CA_CERT
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "10495"
      - key: REDIS_USERNAME
        value: default
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://jobradar.me
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_HOST
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_NAMESPACE
        value: job-posts
